### ISSUE TITLE
Redirect to Main Page

### ISSUE THREAD

**Issue by Vijaykv5** [Caixetadev/cutez#6]
When clicked on The logo, it should redirect to the main page

<img width="1437" alt="Screenshot 2023-09-01 at 7 15 35 PM" src="https://github.com/Caixetadev/cutez/assets/94985341/6375089e-8a62-4d97-a61f-e31369995a59">

**Comment by Caixetadev** [comment]
But this page is already the main page, could you explain what you mean?

**Comment by Vijaykv5** [comment]
Since the logo contains the link , so whenever the user clicks it , he/she should be redirect (if it's also main page, it can render the components)

**Comment by Caixetadev** [comment]
thanks @Vijaykv5
